version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/microservice
    depends_on:
      - database
    container_name: microservice-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M

  database:
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_DATABASE: microservice
    container_name: microservice-db
    ports:
      - 33066:3306
    volumes:
      - microservice-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: microservice-pma


# persisted storage
volumes:
  microservice-data: